__include__: [
  './rtv4_hgnetv2_s_coco.yml'
]

output_dir: ./outputs/rtv4_hgnetv2_s_7classes_anomaly_guided

num_classes: 7
remap_mscoco_category: False

train_dataloader:
  dataset:
    img_folder: /data/processed/ICME/track1compose/images/train
    ann_file: /data/processed/ICME/track1compose/coco_annotations_7classes/instances_train.json
    anomaly_map_dir: /data/usrs/lnj/INP-Former/output/res_nocls/heatmapscore/composenew/train
    anomaly_map_suffix: _anomaly_score.npy
    anomaly_map_use_basename_only: True
  drop_last: True

val_dataloader:
  dataset:
    img_folder: /data/processed/ICME/track1compose/images/val
    ann_file: /data/processed/ICME/track1compose/coco_annotations_7classes/instances_val.json
    anomaly_map_dir: /data/usrs/lnj/INP-Former/output/res_nocls/heatmapscore/composenew/val
    anomaly_map_suffix: _anomaly_score.npy
    anomaly_map_use_basename_only: True
  drop_last: False

HybridEncoder:
  anomaly_guided: True
  anomaly_fusion_weight: 0.5
  anomaly_residual_weight: 0.25
  anomaly_map_minmax_norm: True
